
POST http://localhost:3003/signUp
Content-Type: application/json

{
    "user": "vinicius",
    "email": "vinicius@gmail.com",
    "password": "vinicius123"
}

###

GET http://localhost:3000/client
###