
POST https://viniTodo-production.up.railway.app/signUp
Content-Type: application/json

{
    "user": "vinicius",
    "email": "vinicius@gmail.com",
    "password": "vinicius123"
}

###

GET https://viniTodo-production.up.railway.app/task/


###

POST https://viniTodo-production.up.railway.app/task
Content-Type: application/json

{
    "title": "testando6",
    "status": 0
}

###

PUT https://viniTodo-production.up.railway.app/24b6949b-246a-47a7-b8a5-8403b9d777be
Content-Type: application/json

{
    "status": 0
}

###

DELETE https://viniTodo-production.up.railway.app/task/delete/477524ae-bce5-44c5-8b41-0fd4e632e662